/**
 * Product masterfile column mapping.
 *
 * Hoja1 has price + stock for 743 SKUs.
 * MF_ES/MF_ENG/MF_FR have full product data for 733 SKUs.
 * The mapper joins both by SKU.
 */

export const productMapping = {
  priceSheet: 'Hoja1',
  priceFields: {
    sku: 'Código',
    price: 'Precio Neto Special Buys',
    stock: 'Unidades',
    tipologia: 'Tipologia',
    familia: 'Família',
    description: 'Descripción',
  },

  sheets: {
    es: 'MF_ES',
    en: 'MF_ENG',
    fr: 'MF_FR',
  },

  fields: {
    es: {
      sku: 'Referencia',
      title: 'Descripción',
      tenderText: 'masterfile.tender_text',
      type: 'Tipo',
      ean: 'EAN13',
      familia: 'Família',
      catalogo: 'Catálogo',
      garantia: 'Garantía',
      material: 'Material',
      acabado: 'Acabado',
      largo: 'Largo',
      ancho: 'Ancho',
      alto: 'Alto',
      proyeccion: 'Proyección',
      fuenteLuz: 'Fuente de luz',
      incluyeBombilla: 'Incluye bombilla',
      eficienciaEnergetica: 'Eficiencia energética',
      vatios: 'Vatios (W)',
      lumenes: 'Lúmenes (lm)',
      lumenesReales: 'Lumenes reales (lm)',
      temperatura: 'Temperatura color led (K)',
      cri: 'CRI',
      anguloLuz: 'Rayo luz (º)',
      regulacion: 'Tipo regulación',
      ip: 'IP',
      ik: 'IK',
      pesoNeto: 'Peso neto (KG)',
      pesoEmpaquetado: 'Peso empaquetado (KG)',
      volumenUnidad: 'Volumen unidad (m3)',
      etiquetaVf: 'Etiqueta V/f',
    },
    en: {
      sku: 'Reference',
      title: 'Description',
      tenderText: 'masterfile.tender_text',
      type: 'Type',
      ean: 'EAN13',
      familia: 'Family',
      catalogo: 'Catalog',
      garantia: 'Warranty',
      material: 'Material',
      acabado: 'Finish',
      largo: 'Length',
      ancho: 'Width',
      alto: 'Height',
      proyeccion: 'Projection',
      fuenteLuz: 'Light source',
      incluyeBombilla: 'Bulb included',
      eficienciaEnergetica: 'Energy efficiency',
      vatios: 'Wattage (W)',
      lumenes: 'Lumen Output (lm)',
      lumenesReales: 'Lumenes reales (lm)',
      temperatura: 'Led Colour Temperature (K)',
      cri: 'CRI',
      anguloLuz: 'Light Beam (º)',
      regulacion: 'Regulation type',
      ip: 'IP Rating',
      ik: 'IK',
      pesoNeto: 'Weight net (KG)',
      pesoEmpaquetado: 'Weight packaged (KG)',
      volumenUnidad: 'Volume Unit (m3)',
      etiquetaVf: 'Etiqueta V/f',
    },
    fr: {
      sku: 'Référence',
      title: 'Description',
      tenderText: 'masterfile.tender_text',
      type: 'Type',
      ean: 'EAN13',
      familia: 'Famille',
      catalogo: 'Catalogue',
      garantia: 'Garantie',
      material: 'Matériel',
      acabado: 'Fini',
      largo: 'grand',
      ancho: 'Largeur',
      alto: 'Hauteur',
      proyeccion: 'Projection',
      fuenteLuz: 'Source de lumière',
      incluyeBombilla: 'Inclure une ampoule',
      eficienciaEnergetica: 'Efficacité énergétique',
      vatios: 'Watts (W)',
      lumenes: 'Lumens (lm)',
      lumenesReales: 'Real Lumens (lm)',
      temperatura: 'Température de couleur LED (K)',
      cri: 'CRI',
      anguloLuz: 'Faisceau de lumière (°)',
      regulacion: 'Réglementation de type',
      ip: 'IP',
      ik: 'IK',
      pesoNeto: 'Poids net (kg)',
      pesoEmpaquetado: 'Poids emballé (kg)',
      volumenUnidad: 'Unité de volume (m3)',
      etiquetaVf: 'Étiquette V/F',
    },
  },

  images: {
    es: ['Imagen web', 'Imagen ambiente 1', 'Imagen ambiente 2', 'Imagen ambiente 3', 'Detail Image 1', 'Detail Image 2'],
    en: ['Web Image', 'Ambient Image 1', 'Ambient Image 2', 'Ambient Image 3', 'Detail Image 1', 'Detail Image 2'],
    fr: ['Image Web', 'Image d\'environnement 1', 'Image d\'environnement 2', 'Image d\'environnement 3', 'Image de détail 1', 'Image de détail 2'],
  },

  pdfs: {
    es: {
      ficha: 'Ficha',
      fotometria: 'Fotometría',
      comercial: 'masterfile.ploma_comercial',
      modelo_3d: '3D',
      ies: 'masterfile.ies',
      ldt: 'masterfile.ldt',
      ee: 'EE',
      imc: 'IMC',
    },
    en: {
      ficha: 'Datasheet',
      fotometria: 'Photometry',
      comercial: 'masterfile.ploma_comercial',
      modelo_3d: '3D',
      ies: 'masterfile.ies',
      ldt: 'masterfile.ldt',
      ee: 'EE',
      imc: 'IMC',
    },
    fr: {
      ficha: 'Fiche technique',
      fotometria: 'Photométrie',
      comercial: 'masterfile.ploma_comercial',
      modelo_3d: '3D',
      ies: 'masterfile.ies',
      ldt: 'masterfile.ldt',
      ee: 'EE',
      imc: 'IMC',
    },
  },

  metafields: {
    namespace: 'product',
  },
};
